[project]
name = "ChainClinic"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.doctors-registry]
path = "contracts/doctors-registry.clar"
depends_on = []

[contracts.medical-records]
path = "contracts/medical-records.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
